-- Added 'username' for staff
ALTER TABLE STAFF
ADD USERNAME VARCHAR(16) NOT NULL;


-- Making the corporate member table
CREATE TABLE "CORPORATEMEMBER" (
"CORPORATE_ID" SMALLINT PRIMARY KEY NOT NULL,
"FIRSTNAME" VARCHAR(45) NOT NULL,
"LASTNAME" VARCHAR(45) NOT NULL,
"CORPORATE_TYPEID" VARCHAR(10) NOT NULL,
"EMAIL" VARCHAR(50) NOT NULL,
"MOBILENUMBER" VARCHAR(20) NOT NULL,
"ADDRESS" VARCHAR(50) NOT NULL,
"SUBURB" VARCHAR(20) NOT NULL,
"POSTCODE" VARCHAR(10) NOT NULL,
"STATE" VARCHAR(20) NOT NULL,
"COMPANYNAME" VARCHAR(10) NOT NULL,
"COMPANYNO" VARCHAR(20) NOT NULL,
"COMPANYADDRESS" VARCHAR(50) NOT NULL,
"COM_SUBURB" VARCHAR(20) NOT NULL,
"COM_POSTCODE" VARCHAR(10) NOT NULL,
"COM_STATE" VARCHAR(20) NOT NULL
);

-- Making the 'PCorporateCustomer' table
CREATE TABLE "PCorporateCustomer" (
"PCORPORATEC_ID" SMALLINT PRIMARY KEY NOT NULL,
"FIRSTNAME" VARCHAR(45) NOT NULL,
"LASTNAME" VARCHAR(45) NOT NULL,
"EMAIL" VARCHAR(50) NOT NULL,
"MOBILENUMBER" VARCHAR(20) NOT NULL,
"ADDRESS" VARCHAR(50) NOT NULL,
"SUBURB" VARCHAR(20) NOT NULL,
"POSTCODE" VARCHAR(10) NOT NULL,
"STATE" VARCHAR(20) NOT NULL,
"COMPANYNAME" VARCHAR(10) NOT NULL,
"COMPANYNO" VARCHAR(20) NOT NULL,
"COMPANYADDRESS" VARCHAR(50) NOT NULL,
"COM_SUBURB" VARCHAR(20) NOT NULL,
"COM_POSTCODE" VARCHAR(10) NOT NULL,
"COM_STATE" VARCHAR(20) NOT NULL
);
